DDIT-JINRO/jinro_back

src/main/java/kr/or/ddit/util/file/web/FileController.java
-  파일 다운로드 컨트롤러 추가
-  파일 다운로드 할 시 /files/download post로 호출
- 파라미터 groupId와 seq필요
Closes #{이슈 번호}
#15
=> [feat] 파일 다운로드 컨트롩러 추가

src/main/java/kr/or/ddit/empt/cte/web/CareerTechnicalEducationController.java, src/main/java/kr/or/ddit/empt/ema/web/EmploymentAdvertisementController.java, src/main/java/kr/or/ddit/empt/ema/web/EmploymentPostingController.java, src/main/java/kr/or/ddit/empt/enp/web/EnterprisePostingController.java, src/main/java/kr/or/ddit/empt/ivfb/web/InterviewFeedbackController.java, src/main/resources/static/css/header.css, src/main/webapp/WEB-INF/views/content/main.jsp, src/main/webapp/WEB-INF/views/empt/cte/careerTechnicalEducation.jsp, src/main/webapp/WEB-INF/views/empt/ema/employmentAdvertisement.jsp, src/main/webapp/WEB-INF/views/empt/emp/employmentPosting.jsp, src/main/webapp/WEB-INF/views/empt/enp/enterprisePosting.jsp, src/main/webapp/WEB-INF/views/empt/ivfb/interviewFeedback.jsp
취업 페이지 - 채용공고, 기업정보, 면접후기, 직업교육 페이지 컨트롤러 연결
소메뉴 없음
Closes #27
=> [Feat] 취업 페이지 컨트롤러 연결

.gitignore, src/main/java/kr/or/ddit/ertds/hgschl/web/HighSchoolController.java, src/main/java/kr/or/ddit/ertds/qlfexm/web/QualificationExamController.java, src/main/java/kr/or/ddit/ertds/univ/web/UniversityController.java, src/main/webapp/WEB-INF/views/ertds/hgschl/detail.jsp, src/main/webapp/WEB-INF/views/ertds/hgschl/list.jsp, src/main/webapp/WEB-INF/views/ertds/list.jsp, src/main/webapp/WEB-INF/views/ertds/qlfexm/list.jsp, src/main/webapp/WEB-INF/views/ertds/univ/compare.jsp, src/main/webapp/WEB-INF/views/ertds/univ/detail.jsp, src/main/webapp/WEB-INF/views/ertds/univ/list.jsp, src/main/webapp/WEB-INF/views/ertds/univ/major.jsp
진학파트
대학교, 고등학교, 검정고시 컨트롤러 jsp 생성 및 연결
Closes #24
=> [feat] 진학 파트 컨트롤러 jsp 연결

.gitignore, src/main/resources/application.properties
- application.properties 파일에서 민감 정보 제외
- secret.yml 파일 생성
- secret.yml 파일 gitignore 파일에 추가
Closes #52
=> [chore] 민감 정보 secret.yml 로 제외

src/main/java/kr/or/ddit/config/jwt/JwtAuthenticationFilter.java
jwt 필터 파트 filterChain.doFilter(request, response); 이후 return 누락 수정
Closes #56
=> [fix] 필터 return 누락 수정

src/main/java/kr/or/ddit/com/ComCodeClVO.java, src/main/java/kr/or/ddit/com/ComCodeVO.java, src/main/java/kr/or/ddit/com/FileDetailVO.java, src/main/java/kr/or/ddit/com/FileGroupVO.java
공통으로 자주 쓰이는 VO들 
- ComCode
- ComCodeCL
- FileGroup
- FileDetail
com 패키지 생성후 VO생성
Closes #65
=> [feat] 공통 VO 추가

pom.xml, src/main/java/kr/or/ddit/config/WebConfig.java, src/main/java/kr/or/ddit/util/ai/web/GenerateTextFromTextInput.java, src/main/webapp/WEB-INF/views/AIChat/AIChatUI.jsp, src/main/webapp/WEB-INF/views/aiChat/aiChatUI.jsp
제미나이  챗봇 구현(컨트롤러 , JSP)
Closes #{이슈 번호}
=> [feat] 57 create ai chat

src/main/java/kr/or/ddit/config/SecurityConfig.java, src/main/java/kr/or/ddit/exception/ErrorCode.java, src/main/java/kr/or/ddit/rdm/package-info.java, src/main/java/kr/or/ddit/rdm/service/RoadmapService.java, src/main/java/kr/or/ddit/rdm/service/RoadmapStepVO.java, src/main/java/kr/or/ddit/rdm/service/RoadmapVO.java, src/main/java/kr/or/ddit/rdm/service/impl/RoadmapMapper.java, src/main/java/kr/or/ddit/rdm/service/impl/RoadmapServiceImpl.java, src/main/java/kr/or/ddit/rdm/web/RoadmapController.java, src/main/resources/mybatis/mapper/roadmap-Mapper.xml, src/main/resources/static/js/content/main.js, src/main/webapp/WEB-INF/views/content/main.jsp, src/main/webapp/WEB-INF/views/include/header.jsp
- 기본기능
- 사용자의 로드맵 생성
- 미션 수락 / 완료
- 미션 완료 예정일 등록 / 수정
- 캐릭터 이동
- 로드맵 완성 및 완성 결과 페이지
- 잠금, 진행 중, 완료 상태에 따른 구름 모습
- 편의기능
- 튜토리얼 모달
- 잠금 상태 모달
- 구름 툴팁
- 로드맵 완료 모달
- 완료 예정일 확인을 위한 캘린더
- 진행 중, 완료됨, 완료 뱃지
- 바로가기 버튼
- 미션 완료 모션
- 오늘 하루 안보기 기능
- 이후 수정사항
- 배경 화면 무한 반복
- 완료 구름 애니메이션 추가
- 로드맵 완성 내용 재구성
Closes #49
=> [feat] 유저 로드맵 기능 구현

src/main/java/kr/or/ddit/config/handler/AlarmTypeHandler.java, src/main/java/kr/or/ddit/config/handler/package-info.java, src/main/java/kr/or/ddit/exception/GlobalExceptionHandler.java, src/main/java/kr/or/ddit/prg/std/web/StudyGroupController.java, src/main/java/kr/or/ddit/util/alarm/package-info.java, src/main/java/kr/or/ddit/util/alarm/service/AlarmService.java, src/main/java/kr/or/ddit/util/alarm/service/AlarmType.java, src/main/java/kr/or/ddit/util/alarm/service/AlarmVO.java, src/main/java/kr/or/ddit/util/alarm/service/impl/AlarmEmitterManager.java, src/main/java/kr/or/ddit/util/alarm/service/impl/AlarmMapper.java, src/main/java/kr/or/ddit/util/alarm/service/impl/AlarmServiceImpl.java, src/main/java/kr/or/ddit/util/alarm/web/AlarmController.java, src/main/java/kr/or/ddit/you/web/youtubeApiController.java, src/main/resources/application.properties, src/main/resources/mybatis/mapper/alarm-Mapper.xml, src/main/resources/static/css/alarmModal.css, src/main/resources/static/js/include/alarmModal.js, src/main/webapp/WEB-INF/views/include/alarmModal.jsp, src/main/webapp/WEB-INF/views/include/header.jsp, src/main/webapp/WEB-INF/views/prg/std/stdGroupDetail.jsp
노션에 정리.
1. [노션 Gantt 작업내용](https://www.notion.so/23dea31dbfbd8052abfcfaa4fac9e3ff?v=211ea31dbfbd80a0942d000cbd088683&source=copy_link)
2. [노션 참고문서 알림기능적용법](https://www.notion.so/23fea31dbfbd80c69ff2d741cbab3890?source=copy_link)
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
Closes #76
=> [feat] 알림기능 구현

src/main/java/kr/or/ddit/rdm/service/RoadmapResultRequestVO.java, src/main/java/kr/or/ddit/rdm/service/impl/RoadmapServiceImpl.java, src/main/resources/mybatis/mapper/roadmap-Mapper.xml
- 로드맵 결과 데이터 분석에 사용자 이름 추가
- 필요없는 문구 잘라내어 json 형태만 추출
Closes #146
=> [refactor] 로드맵 결과 데이터에 사용자 이름 추가

src/main/java/kr/or/ddit/cdp/aifdbck/rsm/service/AiFeedbackResumeService.java, src/main/java/kr/or/ddit/cdp/aifdbck/rsm/service/impl/AiFeedbackResumeMapper.java, src/main/java/kr/or/ddit/cdp/aifdbck/rsm/service/impl/AiFeedbackResumeServiceImpl.java, src/main/java/kr/or/ddit/cdp/aifdbck/rsm/web/AiFeedbackResumeController.java, src/main/java/kr/or/ddit/cdp/aifdbck/sint/service/AiFeedbackSelfIntroService.java, src/main/java/kr/or/ddit/cdp/aifdbck/sint/service/SelfIntroFeedbackRequestDto.java, src/main/java/kr/or/ddit/cdp/aifdbck/sint/service/impl/AiFeedbackSelfIntroMapper.java, src/main/java/kr/or/ddit/cdp/aifdbck/sint/service/impl/AiFeedbackSelfIntroServiceImpl.java, src/main/java/kr/or/ddit/cdp/aifdbck/sint/web/AiFeedbackSelfIntroController.java, src/main/resources/mybatis/mapper/AiFeedbackResume-Mapper.xml, src/main/resources/mybatis/mapper/AiFeedbackSelfIntro-Mapper.xml, src/main/resources/static/js/cdp/aifdbck/rsm/aiFeedbackResume.js, src/main/resources/static/js/cdp/aifdbck/sint/aiFeedbackSelfIntro.js
일단 구독을 하지 않았을 경우 페이지에 입장하면 경고창이 뜨고 리스트를 선택할 수 없게 막힌다
그리고 구독을 하였다고 해도 해당 서비스를 다 이용하였다면 ai피드백요청 버튼을 클릭했을시 경고창이 뜨고 ai첨삭기능을 이용할 수 없다
만약 서비스가 남아있고 성공적으로 ai첨삭이 끝나면 남은 서비스 횟수를 알려준다
구독을 하지 않았을 경우
구독은 하였지만 서비스를 다 이용한 경우(ai첨삭 불가)
구독상품에 서비스가 남아있을 경우
Closes #159
=> [Feat] ai 첨삼 구독상품에 따른 제한설정

src/main/java/kr/or/ddit/mpg/pay/service/PaymentService.java, src/main/java/kr/or/ddit/mpg/pay/service/impl/MemberSubscriptionMapper.java, src/main/java/kr/or/ddit/mpg/pay/service/impl/PaymentServiceImpl.java, src/main/java/kr/or/ddit/util/alarm/service/AlarmType.java, src/main/java/kr/or/ddit/util/alarm/service/impl/AlarmServiceImpl.java, src/main/java/kr/or/ddit/util/setle/web/SubscriptionScheduler.java, src/main/resources/mybatis/mapper/memberSubscription-Mapper.xml, src/main/webapp/WEB-INF/views/mpg/pay/selectPaymentView.jsp
오늘이 정기결제 전날인 모두에게 알람 전송
추가적으로 화면에 나오는 날짜형식 yyyy. MM. dd 형태로 변경
Closes #166
=> [Feat] 정기결제 전날 알림기능

src/main/java/kr/or/ddit/prg/act/cr/service/impl/ActivityCareerExpServiceImpl.java, src/main/java/kr/or/ddit/prg/act/sup/service/impl/ActivitySupportersServiceImpl.java, src/main/java/kr/or/ddit/prg/act/vol/service/impl/ActivityVolunteerServiceImpl.java, src/main/java/kr/or/ddit/prg/ctt/service/impl/ContestServiceImpl.java, src/main/resources/static/css/cdp/imtintrvw/aiimtintrvw/aimitationInterview.css, src/main/resources/static/css/cdp/imtintrvw/intrvwqestnmn/interviewQuestionMangement.css, src/main/resources/static/css/cdp/rsm/rsm/resumeList.css, src/main/resources/static/css/cdp/sint/sintlst/selfIntroList.css, src/main/resources/static/css/csc/not/notice.css, src/main/resources/static/css/ertds/qlfexm/selectQlfexmList.css, src/main/resources/static/css/prg/act/vol/volDetail.css, src/main/resources/static/css/prg/std/stdGroupDetail.css, src/main/resources/static/js/csc/not/noticeList.js, src/main/resources/static/js/ertds/qlfexm/selectQlfexmList.js, src/main/webapp/WEB-INF/views/csc/not/noticeList.jsp, src/main/webapp/WEB-INF/views/ertds/qlfexm/selectQlfexmList.jsp, src/main/webapp/WEB-INF/views/prg/act/vol/volDetail.jsp, src/main/webapp/WEB-INF/views/prg/std/stdGroupList.jsp
- 공지사항, 검정고시 hover 수정 및 div단 클릭 시 상세 페이지 이동
- 공모전, 인턴십 등 상세요강 정렬 수정
Closes #169
=> [Feat] 운영페이지 부분 css및 service 수정

src/main/java/kr/or/ddit/admin/las/service/ContentStatsService.java, src/main/java/kr/or/ddit/admin/las/service/impl/ContentStatsMapper.java, src/main/java/kr/or/ddit/admin/las/service/impl/ContentsStatsServiceImpl.java, src/main/java/kr/or/ddit/admin/las/web/ContentStatsController.java, src/main/resources/mybatis/mapper/contentStats-Mapper.xml, src/main/resources/static/css/admin/las/contentUsageStatistics.css, src/main/resources/static/js/include/admin/las/accessUsageStatistics.js, src/main/resources/static/js/include/admin/las/contentUsageStatistics.js, src/main/webapp/WEB-INF/views/admin/las/contentUsageStatistics.jsp
북마크 카테고리별 횟수 통계. 연령대별 성별 기간별 적용
북마크 TOP 자료 -> 막대 클릭시 해당 페이지 새탭에 표시.
Closes #157
=> [feat] 로그통계 컨텐츠관리 좌측 북마크관련 자료.

src/main/resources/static/css/main.css, src/main/resources/static/js/content/main.js, src/main/webapp/WEB-INF/views/content/main.jsp, src/main/webapp/WEB-INF/views/include/footer.jsp
- 메인 페이지에 빠져있는 버튼 기능 추가
- roadmap 이동 버튼 구현
- worldcup 이동 버튼 구현
- 심리검사 페이지 이동 버튼 구현
Closes #175
=> [feat] 메인페이지에서 각 기능 버튼 구현

src/main/java/kr/or/ddit/csc/inq/service/impl/InqServiceimpl.java, src/main/resources/mybatis/mapper/inq-Mapper.xml, src/main/resources/static/css/csc/inq/insertInq.css, src/main/resources/static/js/csc/inq/InqList.js, src/main/resources/static/js/csc/inq/insertInq.js, src/main/webapp/WEB-INF/views/csc/inq/inqryList.jsp, src/main/webapp/WEB-INF/views/csc/inq/insertInq.jsp
원래 공개 비공개 글이 나누어 있던것을 본인이 작성한 글만 나오게 수정
본인 글이 있을 경우
본인 글이 없을 경우
Closes #178
=> [reafactor] 1대1 문의리스트 설정 변경

src/main/resources/mybatis/mapper/paymentStats-Mapper.xml
수정 전에 기준이 월초로 되어 있던 것을 월말로 수정해서 월별 이용자 통계 그래프와 기준을 일치
수정후
Closes #210
=> Feat 210 pay query

src/main/resources/static/css/cdp/imtintrvw/intrvwqestnmn/interviewQuestionWriting.css, src/main/resources/static/css/cdp/sint/sintwrt/selfIntroWriting.css, src/main/resources/static/js/cdp/imtintrvw/intrvwqestnmn/interviewQuestionWriting.js, src/main/resources/static/js/cdp/sint/qestnlst/questionList.js, src/main/resources/static/js/cdp/sint/sintwrt/selfIntroWriting.js, src/main/webapp/WEB-INF/views/cdp/imtintrvw/intrvwqestnlst/intrvwQuestionList.jsp, src/main/webapp/WEB-INF/views/cdp/sint/qestnlst/questionList.jsp
- js의 클래스 수정(자동완성 관련 클래스/ 삭제기능 관련 클래스)
- 자기소개서와 면접질문 작성 페이지의 자동완성 버튼 클래스를 이력서의 버튼과 일치
자기소개서 자동완성
모의면접 자동완성
Closes #213
=> [feat] 자동완성 코드 수정

src/main/java/kr/or/ddit/cdp/aifdbck/rsm/web/AiFeedbackResumeController.java, src/main/java/kr/or/ddit/cdp/aifdbck/sint/web/AiFeedbackSelfIntroController.java, src/main/java/kr/or/ddit/cnslt/aicns/web/AICounselingController.java, src/main/java/kr/or/ddit/cnslt/resve/crsv/web/CounselingReserveController.java, src/main/resources/static/css/cdp/aifdbck/rsm/aiFeedbackResume.css, src/main/resources/static/css/cdp/aifdbck/sint/aiFeedbackSelfIntro.css, src/main/resources/static/css/cnslt/aicns/aicns.css, src/main/resources/static/css/cnslt/resve/crsv/counselingreserveDetail.css, src/main/resources/static/js/cdp/aifdbck/rsm/aiFeedbackResume.js, src/main/resources/static/js/cdp/aifdbck/sint/aiFeedbackSelfIntro.js, src/main/resources/static/js/cnslt/resve/crsv/counselingreserveDetail.js, src/main/webapp/WEB-INF/views/cdp/aifdbck/rsm/aiFeedbackResume.jsp, src/main/webapp/WEB-INF/views/cdp/aifdbck/sint/aiFeedbackSelfIntro.jsp, src/main/webapp/WEB-INF/views/cnslt/aicns/aicns.jsp, src/main/webapp/WEB-INF/views/cnslt/resve/crsv/counselingreserveDetail.jsp
ai첨삭, 상담예약, ai첨삭을 버튼을 클릭했을때 남은 이용권 수가 나타나게 모달 생성
[노션 이미지 참고](https://www.notion.so/255ea31dbfbd8005af6ff37fa0e6981a)
Closes #220
=> [Feat] 구독 서비스 모달

src/main/java/kr/or/ddit/admin/las/service/PaymentStatsService.java, src/main/java/kr/or/ddit/admin/las/service/impl/PaymentStatsMapper.java, src/main/java/kr/or/ddit/admin/las/service/impl/PaymentStatsServiceImpl.java, src/main/java/kr/or/ddit/admin/las/web/PaymentStatsController.java, src/main/resources/mybatis/mapper/paymentStats-Mapper.xml, src/main/resources/static/css/admin/las/paymentStatistics.css, src/main/resources/static/js/include/admin/las/paymentStatistics.js, src/main/webapp/WEB-INF/views/admin/las/paymentPremiumServiceStatistics.jsp
- css 배치 제외하고 구현 완료
- 데이터 로딩
- 차트 js 구현
- 정렬 및 필터링 구현
Closes #227
=> [feat] 결제 통계 페이지 구현

src/main/java/kr/or/ddit/comm/peer/teen/service/impl/TeenCommServiceImpl.java, src/main/resources/mybatis/mapper/careerEncyclopedia-Mapper.xml, src/main/resources/mybatis/mapper/comm-Mapper.xml, src/main/resources/static/js/cnslt/aicns/aicns.js, src/main/webapp/WEB-INF/views/cnslt/aicns/aicns.jsp, src/main/webapp/WEB-INF/views/comm/path/pathList.jsp
또래게시판 페이징
이력서템플릿게시판 페이징
상담내역 필터 오작동 
진로진학 게시판 검색 오작동
AI상담 에러
Closes #248
=> [Fix] 자잘한 에러수정
